





CREATE TABLE `doctor` (
  `NOMBRE_DOCTOR` varchar(150) NOT NULL,
  `APELLIDO_DOCTOR` varchar(150) NOT NULL,
  `ESTADO` bit(1) NOT NULL,
  `ESPECIALIDAD` varchar(50) DEFAULT NULL,
  `ID_DOCTOR` char(10) NOT NULL,
  PRIMARY KEY (`ID_DOCTOR`)
) ;

CREATE TABLE `expediente` (
  `IDEXPEDIENTE` varchar(15) NOT NULL,
  `NOMBRE_PACIENTE` varchar(150) NOT NULL,
  `APELLIDO_PACIENTE` varchar(150) NOT NULL,
  `TELEFONO` int(11) NOT NULL,
  `SEXO` varchar(10) NOT NULL,
  `FECHA_NACIEMIENTO` date NOT NULL,
  PRIMARY KEY (`IDEXPEDIENTE`)
) ;
CREATE TABLE `cita` (
  `ID_CITA` varchar(15) NOT NULL,
  `ID_HORARIO` varchar(15) DEFAULT NULL,
  `IDEXPEDIENTE` varchar(15) DEFAULT NULL,
  `DOCTOR` varchar(150) NOT NULL,
  `COMENTARIO` varchar(255) NOT NULL,
  PRIMARY KEY (`ID_CITA`),
  KEY `FK_CITA_EXPEDIENTE` (`IDEXPEDIENTE`),
  KEY `FK_HORARIO_CITA` (`ID_HORARIO`),
  CONSTRAINT `FK_CITA_EXPEDIENTE` FOREIGN KEY (`IDEXPEDIENTE`) REFERENCES `expediente` (`IDEXPEDIENTE`),
  CONSTRAINT `FK_HORARIO_CITA` FOREIGN KEY (`ID_HORARIO`) REFERENCES `horario` (`ID_HORARIO`)
) ;



CREATE TABLE `especialidad` (
  `ID_ESPECIALIDAD` char(15) NOT NULL,
  `NOMBRE_ESPECIALIDAD` char(200) NOT NULL,
  PRIMARY KEY (`ID_ESPECIALIDAD`)
) ;

CREATE TABLE `doctor_especialidad` (
  `ID_ESPECIALIDAD` varchar(15) NOT NULL,
  `ID_DOCTOR` varchar(10) NOT NULL,
  PRIMARY KEY (`ID_ESPECIALIDAD`),
  KEY `FK_DOCTOR_ESPECIALIDAD2` (`ID_DOCTOR`),
  CONSTRAINT `FK_DOCTOR_ESPECIALIDAD` FOREIGN KEY (`ID_ESPECIALIDAD`) REFERENCES `especialidad` (`ID_ESPECIALIDAD`),
  CONSTRAINT `FK_DOCTOR_ESPECIALIDAD2` FOREIGN KEY (`ID_DOCTOR`) REFERENCES `doctor` (`ID_DOCTOR`)
) ;




CREATE TABLE `doctor_horario` (
  `ID_HORARIO` varchar(15) NOT NULL,
  `ID_DOCTOR` varchar(10) NOT NULL,
  PRIMARY KEY (`ID_HORARIO`),
  KEY `FK_DOCTOR_HORARIO2` (`ID_DOCTOR`),
  CONSTRAINT `FK_DOCTOR_HORARIO` FOREIGN KEY (`ID_HORARIO`) REFERENCES `horario` (`ID_HORARIO`),
  CONSTRAINT `FK_DOCTOR_HORARIO2` FOREIGN KEY (`ID_DOCTOR`) REFERENCES `doctor` (`ID_DOCTOR`)
) ;







CREATE TABLE `horario` (
  `ID_HORARIO` varchar(15) NOT NULL,
  `HORA` varchar(9) NOT NULL,
  `JORNADA` varchar(30) NOT NULL,
  `FECHA` date NOT NULL,
  PRIMARY KEY (`ID_HORARIO`)
) ;


CREATE TABLE `usuario` (
  `ID_USUARIO` varchar(15) NOT NULL,
  `NOMBRE_USUARIO` varchar(150) NOT NULL,
  `APELLIDO_USUARIO` varchar(150) NOT NULL,
  `TIPO_USUARIO` varchar(10) NOT NULL,
  `CONTRASENA` varchar(100) NOT NULL,
  `CORREO` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_USUARIO`)
) ;

